# This page is used to automatically generate the Professional Training table in the file pages/cv.md
######################################


- subject: "Professional Certificate in Data Science"
  provider: "Harvard University, USA"
  year: "2021"

- subject: "Data Analytics in Power BI"
  provider: "Coursera, USA"
  year: "2021"

- subject: "Getting Started with Power BI Desktop"
  provider: "Coursera, USA"
  year: "2021"

- subject: "Privacy Law and Data Protection"
  provider: "University of Pennsylvania, UPENN, USA"
  year: "2021"

- subject: "Data-driven Astronomy"
  provider: "The University of Sydney, Austrália"
  year: "2020"

- subject: "Introduction to Astronomy"
  provider: "Federal Institute Farroupilha, Brazil"
  year: "2020"

- subject: "Learning Psychology"
  provider: "Federal Institute of Rio Grande do Sul, Brazil"
  year: "2020"

- subject: "Basic Coding with Java I"
  provider: "Federal Institute of Rio Grande do Sul, Brazil"
  year: "2020"

- subject: "Educational and Interdisciplinary Projects"
  provider: "Federal Institute of Rio Grande do Sul, Brazil"
  year: "2020"

- subject: "Course in Webdesigner"
  provider: "Prime Cursos, Brazil"
  year: "2020"

- subject: "Database 1: Fundamentals"
  provider: "Federal Institute of Rio Grande do Sul, Brazil"
  year: "2020"

- subject: "Python"
  provider: "Prime Cursos, Brazil"
  year: "2020"

- subject: "Meaningful Learning"
  provider: "Federal Institute of Rio Grande do Sul, Brazil"
  year: "2020"

- subject: "Distance Education"
  provider: "Federal Institute of Rio Grande do Sul, Brazil"
  year: "2020"

- subject: "Modern Pedagogical Approach for Distance Education"
  provider: "Federal Institute of Rio Grande do Sul, Brazil"
  year: "2020"

- subject: "Personalization of Teaching from Active Methodologies"
  provider: "Federal Institute of Rio Grande do Sul, Brazil"
  year: "2020"

- subject: "Course in Cosmology"
  provider: "Federal University of Rio Grande do Sul, UFRGS, Brazil"
  year: "2019"